app:
  data_dir: "./data"
  db_name: "infofinder.db"
  sqlcipher: true        # try SQLCipher if available
  password_prompt: true  # if true, prompt at startup (or read from ENV INFOFINDER_PASSWORD)
  exclude_patterns:
    - "node_modules"
    - ".git"
    - "*.tmp"
    - "*.log"
indexing:
  batch_size: 64
  max_ocr_image_dim: 3000     # px
  file_types: ["txt", "md", "pdf", "png", "jpg", "jpeg"]
  concurrency: 2              # workers for pipeline
  watch_paths: []             # seed folders via API
embeddings:
  model_name: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  normalize: true
search:
  faiss_top_k: 50
  bm25_top_k: 50
  fusion_top_k: 20
  alpha: 0.6   # weight for FAISS in score fusion
security:
  kdf: "argon2id"     # fallback: pbkdf2
  argon2:
    time_cost: 3
    memory_cost: 65536
    parallelism: 2
    hash_len: 32
  pbkdf2:
    iterations: 310000
  aes_gcm_nonce_bytes: 12
